POST http://localhost:8080/cars
Content-Type: application/x-www-form-urlencoded
renterId: 1

plate=AA112&mark=Ford&model=Focuse&color=blue&yearOfProduction=2017&cost=100&imgLink=asdasdwqdasdqwdasdqwdasdqwdsadq

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}


###
GET http://localhost:8080/cars/1

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 400, "Response status is not 400");
});
%}

###
GET http://localhost:8080/cars

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 400, "Response status is not 400");
});
%}

###
DELETE http://localhost:8080/cars/2

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
GET http://localhost:8080/cars?mark=F

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 400, "Response status is not 400");
});
%}

###
GET http://localhost:8080/cars/2/termines

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 400, "Response status is not 400");
});
%}

###
GET http://localhost:8080/cars/renter/1


> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 400, "Response status is not 400");
});
%}

###
PATCH http://localhost:8080/cars/2
Content-Type: application/x-www-form-urlencoded
renterId: 1

plate=AA112&mark=BMW&model=m2&color=metalblue&yearOfProduction=2017&cost=100&imgLink=asdasdwqdasdqwdasdqwdasdqwdsadq

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 201");
  client.assert(response.body.hasOwnProperty("slotId"), 'Can not find the slotId');
});
%}

###
POST http://localhost:8080/cars/1
Content-Type: application/x-www-form-urlencoded
rating: 4

plate=AA112&mark=Ford&model=Focuse&color=blue&yearOfProduction=2017&cost=100&imgLink=asdasdwqdasdqwdasdqwdasdqwdsadq

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}


###
POST http://localhost:8080/cars/carHistories
Content-Type: application/x-www-form-urlencoded
carId: 3

registrationDate=2018-09-26&breaksStatus=good&frontGlassStatus=good&wheelStatus=bad&engineStatus=fine&kmPassed=220000&description=LOrese Fokume dorum lo iso ena kazamanionime!

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}


###
GET http://localhost:8080/cars/carHistories/1
Content-Type: application/x-www-form-urlencoded


> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}


###
DELETE http://localhost:8080/cars/carHistories/2
Content-Type: application/x-www-form-urlencoded


> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}


###