POST http://localhost:8080/clients
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJoZXJvIiwiaWF0IjoxNTg4ODExODM4LCJleHAiOjE1ODg4OTgyMzh9.bZ4E-VMs9P5UqYDMuqdhGcSKlrEdhvnAKtzqoxwzzoJvE8tRLo8Obw1NnCodKTGw84Dw5jn91eItdrLbLrPpVA
Content-Type: application/x-www-form-urlencoded

embg=2512997464018&firstName=Tole&lastName=Jovanov&age=22&sex=female&driverLicenceNumber=Aa323OS&crimeRecord=true&imgUrl=https://i.pinimg.com/originals/6f/a2/5f/6fa25f61d325b980f7b602136b18d0e7.png

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}


###
GET http://localhost:8080/clients/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJoZXJvIiwiaWF0IjoxNTg4ODExODM4LCJleHAiOjE1ODg4OTgyMzh9.bZ4E-VMs9P5UqYDMuqdhGcSKlrEdhvnAKtzqoxwzzoJvE8tRLo8Obw1NnCodKTGw84Dw5jn91eItdrLbLrPpVA


> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 400, "Response status is not 400");
});
%}

###
GET http://localhost:8080/clients
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJoZXJvIiwiaWF0IjoxNTg4ODExODM4LCJleHAiOjE1ODg4OTgyMzh9.bZ4E-VMs9P5UqYDMuqdhGcSKlrEdhvnAKtzqoxwzzoJvE8tRLo8Obw1NnCodKTGw84Dw5jn91eItdrLbLrPpVA

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 400, "Response status is not 400");
});
%}

###
DELETE http://localhost:8080/clients/1

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
GET http://localhost:8080/clients?firstName=l

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 400, "Response status is not 400");
});
%}

###
POST http://localhost:8080/clients/follow
clientId: 1
renterId: 1

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 400, "Response status is not 400");
});
%}

###
POST http://localhost:8080/clients/unFollow
clientId: 2
renterId: 1

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 400, "Response status is not 400");
});
%}

###
PATCH http://localhost:8080/clients/2
Content-Type: application/x-www-form-urlencoded

embg=25129971264229&firstName=Simeon&lastName=Mancev&age=21&sex=male&driverLicenceNumber=Aa323OS&crimeRecord=false&imgUrl=someurl

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 201");
  client.assert(response.body.hasOwnProperty("slotId"), 'Can not find the slotId');
});
%}

###