POST http://localhost:8080/renters
Content-Type: application/x-www-form-urlencoded

embg=2222197424029&firstName=Ilija&lastName=Anglov&age=21&sex=male&imgUrl=someurl

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}


###
GET http://localhost:8080/renters/1

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 400, "Response status is not 400");
});
%}

###
GET http://localhost:8080/renters

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 400, "Response status is not 400");
});
%}

###
DELETE http://localhost:8080/renters/1

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
GET http://localhost:8080/renters?name=T

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 400, "Response status is not 400");
});
%}

###
GET http://localhost:8080/renters/followers/2

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 400, "Response status is not 400");
});
%}

###
PATCH http://localhost:8080/renters/1
Content-Type: application/x-www-form-urlencoded

embg=2222222222222&firstName=Ilija&lastName=Angelov&age=22&sex=male&imgUrl=https://cf.shopee.vn/file/4d35935d45b122f3e0851d9d912a825e

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 201");
  client.assert(response.body.hasOwnProperty("slotId"), 'Can not find the slotId');
});
%}

###