POST http://localhost:8080/renters
Content-Type: application/x-www-form-urlencoded

embg=2522197424029&name=Tadej&age=31&sex=male

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}


###
GET http://localhost:8080/renters/2

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 400, "Response status is not 400");
});
%}

###
GET http://localhost:8080/renters

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 400, "Response status is not 400");
});
%}

###
DELETE http://localhost:8080/renters/2

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
GET http://localhost:8080/renters?name=T

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 400, "Response status is not 400");
});
%}

###
GET http://localhost:8080/renters/followers/1

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 400, "Response status is not 400");
});
%}

###
PATCH http://localhost:8080/renters/5
Content-Type: application/x-www-form-urlencoded

embg=2222222222222&name=JJ&age=22&sex=male

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 201");
  client.assert(response.body.hasOwnProperty("slotId"), 'Can not find the slotId');
});
%}

###